apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-demo-app
  namespace: default
spec:
  replicas: 0
  selector:
    matchLabels:
      app: cron-demo-app
  template:
    metadata:
      labels:
        app: cron-demo-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
