apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-probe-demo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: liveness-demo

  template:
    metadata:
      labels:
        app: liveness-demo

    spec:
      containers:
      - name: nginx
        image: nginx

        ports:
        - containerPort: 80

        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy

          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
