apiVersion: v1
kind: Pod
metadata:
  name: pvc-demo

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: my-storage
      mountPath: /data

  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: demo-pvc
