apiVersion: batch/v1
kind: Job
metadata:
  name: order-publisher
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: publisher
          image: order-publisher:latest
          imagePullPolicy: Never
          args: ["50"]
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
      restartPolicy: Never
  backoffLimit: 1
