apiVersion: v1
kind: Pod
metadata:
  name: emptydir-demo

spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: shared-storage
      mountPath: /data

  volumes:
  - name: shared-storage
    emptyDir: {}
